69 use default config file if no file provided at prog call
u413-284-si/webserv pull request #105
Opened 2024-12-12 18:58 UTC by gwolf-011235

### Overview

1. Adds macro DEFAULT_CONFIG_PATH 
2. Adds macros STRINGIZE() and XSTRINGIZE()

#### 1.  Macro DEFAULT_CONFIG_PATH
The value of this macro is used, when no config file path is provided. Macro is used so it can be overwritten at compile time. Has default value of ./config_files/standard_config.conf

Main now accepts zero or one args.

#### 2. Macros STRINGIZE() and XSTRINGIZE()
When an alternative path is provided at compile time via -D one would have to use escaped double quotes: the preprocessor just substitutes the value. This means `-D DEFAULT_CONFIG_PATH=./other/path` would not work > it would replace DEFAULT_CONFIG_PATH with ./other/path, which is not a string literal (since no quotes) and it wouldn't compile. With these two macros the value gets expanded and then stringized. This is also the reason why the default value of DEFAULT_CONFIG_PATH is not put in quotes.

2024-12-13 17:08 UTC, u413-284-si approved these changes
What kind of devilry is this

2024-12-16 09:59 UTC, QCHR1581 requested changes
Works great!

Current default config file causes segfault, but this know and fixed in upcoming PR for parsing. 

Only found a typo.

2024-12-16 09:59 UTC, QCHR1581 commented on src/main.cpp
> + * to be a string one would have to put the vlue in escaped double quotes. This macro in combination with STRINGIZE(s)
Typo: "value"

2024-12-16 10:23 UTC, gwolf-011235 commented on src/main.cpp
> + * to be a string one would have to put the vlue in escaped double quotes. This macro in combination with STRINGIZE(s)
Changed!

2024-12-16 10:26 UTC, QCHR1581 approved these changes

2024-12-16 10:55 UTC, merged