115 percent encoding normalisation
u413-284-si/webserv pull request #118
Opened 2024-12-20 19:01 UTC by gwolf-011235

Adds new function RequestParser::decodePercentEncoding() to decode percent encoded URI.

According to RFC 3986 Sect 2.1. [[LINK](https://datatracker.ietf.org/doc/html/rfc3986#section-2.1)] char outside of the allowed set are percent encoded. This meachnism is relatively simple: create a triplet consisting of '%' and two hexadecimal digits representing the numeric value. Examples:
- space ' ' has hex value of 20 (= 32 in decimal), so it becomes %20. 
- 'ö' is represented in UTF-8 with 0xC3 and 0xB6. Precent encoded it is %C3%B6 (so two triplets)

Implementation iterates through string. If it finds '%' it converts the next two chars to hex and adds the decoded char. Three error cases are handled:
1. A malformed encoding % not followed by two numbers > needs to be a triplet
2. "%00" as this would translate to zero terminator, which could cause some weird behavior. See also Sect 7.3. Back-end transcoding [LINK](https://datatracker.ietf.org/doc/html/rfc3986#section-7.3) which allows rejecting if we are not expecting raw data in component. 
3. A triplet which does consist of non hex chars like "%3$"

RequestParser now also allows '%' as valid URI char. After URI has been split into parts path, query and fragment they get decoded.

Added unittests and integration tests. Also added new test image "grüne äpfel.jpg" for testing.

2024-12-23 18:20 UTC, QCHR1581 approved these changes
Works great! 

Clear structured approach and also handling special case ``%00``.

2024-12-24 16:08 UTC, u413-284-si requested changes
Good job!
The logic of the decoding function can be simplified as suggested. Nice tests!

2024-12-27 12:50 UTC, gwolf-011235 commented on src/RequestParser.cpp
> +		if (*iter == '%' && std::distance(iter, encoded.end()) >= 3) {
True that! Adapted as suggested

2024-12-27 22:04 UTC, u413-284-si approved these changes

2024-12-28 09:18 UTC, merged