Feat add more integration tests
u413-284-si/webserv pull request #125
Opened 2024-12-31 16:07 UTC by gwolf-011235

### Overview

1. restructure integration tests, significantly reducing execution time
2. fix small bug: add content-length header even when size == 0
3. adapt Makefile to also pass NAME to pytest 
4. add some integration tests

### 1. Restructure integration tests

Created new module "utils" with a utils.py to store common used functions:
- start_server() - start server
- stop_server() - stop server
- wait_for_startup() - We now don't wait for delay_time until server starts. We send several test requests within a timeout period. If server does not start within timeout, whole testrun is stopped. If timeout is to short (e.g.  for coverage) it can easily be increased
- make_request() - wrapper for request.get/.post/.delete. Raises pytest.fail() with pytrace=False to minimize length of error if an requests exception is thrown
- parse_http_response() - moved from test_invalid.py

Functions can be imported with e.g. `from utils.utils import start_server`

I (well actually ChatGPT) also added type annotations. Python is dynamically typed, but we can add type info. This speeds up execution time (immensely). Also added docstrings for functions.

In test_signal.py we don't wait seconds until process terminates, but now just .wait on the process itself

All in all drops execution time from ~6-9 seconds to <1 second

### 2. Bugfix

We only added content-length header if the response actually had a body. This lead to the client waiting for the response body, if response had status 200 OK but body was empty. There are some status codes which are defined to have no body (like 204 No content - we don't have any of them implemented right now). For other status codes a "content-length: 0" is recommended. 

Now content-length is always added and only content-type is depedant on !body.empty().

Used for server startup health check: we have a location /health which returns 200 with empty body. I think this is a fast way to check if server is up: we don't even need to open and send a file.

### 3. Adapt Makefile

Makefile now passes $(NAME) to pytest targets test2 and coverage2. This way we can also easily use webserv_sani (compiled with sanitizers) for integration tests.
Also added new var CONFIGFILE to be able to customize which configfile is used.
And renamed variables for kcov to be more explicit:
- COV_DIR > KCOV_DIR
- EXCL_PATH > KCOV_EXCL_PATH

### 4. Add more integration tests

Added more tests. 
I also split up the test files to
- CGI
- GET
- POST
- error3xx
- error4xx
- error5xx

Subdivision might be a bit too much (maybe just one file for errors?). On the other hand this way we systematically order tests.

2025-01-09 22:40 UTC, u413-284-si reviewed
Some parts need clarification. Otherwise comprehensible restructuring of the tests. Nice that the execution time has been reduced significantly!

2025-01-09 22:42 UTC, u413-284-si requested changes
The comment option does not count as review apparently, so here goes...

2025-01-10 17:21 UTC, gwolf-011235 commented on Makefile
> +	./$(NAME) $(CONFIGFILE)
Variable value of CONFIGFILE to valid_config is temporary solution.

However with variable itself we can quickly change config file: `make run CONFIGFILE=./config_files/standard_config.conf`

2025-01-10 17:22 UTC, gwolf-011235 commented on test/integration/server_management/test_signal.py
> +    config_file = config_file = request.config.getoption("--config-file")
Changed

2025-01-10 17:26 UTC, gwolf-011235 commented on test/integration/server_management/test_signal.py
> +# def test_signal_forced_shutdown(request):
I forgot to add an issue for that :D

Right now when we exit from server via catched signal we always return 0. We could also return 128 + signal number to be explicit what signal we received. This test would check that server is shutdown forcefully via SIGINT and that it returns correct number.

I could also assert a 0 so that we just use it for coverage.

Issue is more of a P3.

2025-01-12 10:09 UTC, u413-284-si commented on test/integration/server_management/test_signal.py
> +# def test_signal_forced_shutdown(request):
We can have an issue for that and mark it as P3. Then we will see if we implement it

2025-01-12 11:01 UTC, gwolf-011235 commented on test/integration/server_management/test_signal.py
> +# def test_signal_forced_shutdown(request):
Created issue

2025-01-13 17:02 UTC, u413-284-si approved these changes

2025-01-24 16:59 UTC, merged