79 custom error pages
u413-284-si/webserv pull request #85
Opened 2024-09-29 15:44 UTC by gwolf-011235

### Summary
1. Support for custom error pages
2. Added sample custom error pages to static website
3. Fix: redirect from TargetResourceHandler is stored in Location Header
4. Small things

### 1. Support custom error pages
- ResponseBodyHandler checks if it finds a custom error page.
- Implemented logic to fetch custom one and use it instead of the default ones
- Added tests

### 2. Static website
- Static website has new folder error with two error pages:
  - 404 File not found
  - 403 Forbidden 

### 3. Fix
- In case of a directory which is accessed without '/' an automatic redirect is initiated
- Beforehand this was stored in targetResource, which caused problems: it got overwritten by ResponseBodyHandler
- Now is stored in Location header, which gets inserted. Since this header is only used in response, even an existing one can be safely overwritten

### 4. Small things
- Added configuration entries for custom error pages in the dummy configuration
- Added new status code 308 Permanent Redirect (not used right now, but delimits 3xx error codes)
- Moved the declaration for `getDefaultErrorPage` from utilities to `ResponseBodyHandler`. Also added "test" to increase code coverage -> management move!

2024-09-30 21:04 UTC, u413-284-si requested changes
Looks good, like the custom pages! 

One minor comment, regarding passed parameters.

2024-10-01 06:24 UTC, gwolf-011235 commented on inc/ResponseBodyHandler.hpp
> +	Connection& m_connection;
m_request is a refrence to connection.m_request.
It's there to shorten every `connection.m_request` to just `m_request`:

Eg:
```
[....]
if (m_request.httpStatus >= StatusMovedPermanently) {
		handleErrorBody();
	} else if (m_request.hasAutoindex) {
		AutoindexHandler autoindexHandler(m_fileSystemPolicy);
		m_responseBody = autoindexHandler.execute(m_request.targetResource);
		if (m_responseBody.empty()) {
			m_request.httpStatus = StatusInternalServerError;
			handleErrorBody();
			return;
		}
		m_request.httpStatus = StatusOK;
		m_request.targetResource += "autoindex.html";
[...]
```

vs:
```
[...]
if (connection.m_request.httpStatus >= StatusMovedPermanently) {
		handleErrorBody();
	} else if (connection.m_request.hasAutoindex) {
		AutoindexHandler autoindexHandler(m_fileSystemPolicy);
		m_responseBody = autoindexHandler.execute(connection.m_request.targetResource);
		if (m_responseBody.empty()) {
			connection.m_request.httpStatus = StatusInternalServerError;
			handleErrorBody();
			return;
		}
		connection.m_request.httpStatus = StatusOK;
		connection.m_request.targetResource += "autoindex.html";
[...]
```

Makes it more readable, don't you think?

2024-10-01 06:24 UTC, gwolf-011235 commented on src/ResponseBodyHandler.cpp
> +	, m_request(connection.m_request)
See above

2024-10-01 06:24 UTC, gwolf-011235 commented on src/ResponseBodyHandler.cpp
> +	targetResourceHandler.execute(m_connection, m_request);
This would mean a refactor of `TargetResourceHandler::execute()`.

This is done in #87

2024-10-01 13:23 UTC, QCHR1581 approved these changes
Cool custom pages! Appreciate the Rickroll :)

Nothing additional from my side.

2024-10-02 19:20 UTC, u413-284-si commented on inc/ResponseBodyHandler.hpp
> +	Connection& m_connection;
If you prefer, I am also fine with it. Not an important point

2024-10-02 19:21 UTC, u413-284-si commented on src/ResponseBodyHandler.cpp
> +	targetResourceHandler.execute(m_connection, m_request);
Yep, saw that afterwards when reviewing #87

2024-10-02 19:21 UTC, u413-284-si approved these changes

2024-10-27 20:50 UTC, merged